### ISSUE TITLE
量化VGG16模型

### ISSUE THREAD

**Issue by PQ-girl** [Jermmy/pytorch-quantization-demo#11]
你好，我想要量化vgg16模型，我应该改那部分呀，module.py文件里改的是不是很多

**Comment by Jermmy** [comment]
您好，您的邮件已收到，我会尽快查看。

**Comment by Jermmy** [comment]
vgg16手工改的话，确实需要改挺多的。可以试试我用fx实现的那块分支的代码：https://github.com/Jermmy/pytorch-quantization-demo/blob/test_fx/model.py
这部分的原理我在博客里面有描述：
https://mp.weixin.qq.com/s?__biz=Mzg4ODA3MDkyMA==&mid=2247484547&idx=1&sn=76d38cc341207c502d473204afd23ddd&chksm=cf81f2e4f8f67bf21bd33f6b1ceeb365bed80097adc82677a01dc719c5f5ea8c40dcb24f4f00&scene=178&cur_album_id=1648871870714200067#rd
