### ISSUE TITLE
请问这里的x.clone()是什么用意呢？

### ISSUE THREAD

**Issue by crazy-JiangDongHua** [Jermmy/pytorch-quantization-demo#18]
https://github.com/Jermmy/pytorch-quantization-demo/blob/ac7298f2b5f9cbaa9125ff58c40645ce1f381101/module.py#L270

**Comment by Jermmy** [comment]
因为下一行 x[x < self.qi.zero_point] = self.qi.zero_point 是 inplace 的改动，为了不破坏输入数据，所以先 clone 一份。

**Comment by crazy-JiangDongHua** [comment]
原来如此，涨知识了，感谢博主
