### ISSUE TITLE
关于load量化好模型的问题

### ISSUE THREAD

**Issue by Aaronhuang-778** [Jermmy/pytorch-quantization-demo#22]
hello码主，我测试的时候发现不用quantize_forward矫正模型
直接load已量化模型的模型（先freeze再save的已量化模型），发现模型dict对不上，请问博主是否有教程如何直接load已量化模型做推理而不使用train做矫正吗～

**Comment by Jermmy** [comment]
save之前先不要freeze，然后load之后再做freeze试试
