### ISSUE TITLE
为什么训练过程中fold BN

### ISSUE THREAD

**Issue by CheungBH** [Jermmy/pytorch-quantization-demo#23]
如题。我看到你在训练的forward里面进行了BN folding。
https://github.com/Jermmy/pytorch-quantization-demo/blob/8dc1f8da75ad0ff3110eec57b96c846cd41d3462/module.py#L399
我想知道这么做的意图是什么。BN folding不是训完得到checkpoint才进行的么

**Comment by Jermmy** [comment]
您好，您的邮件已收到，我会尽快查看。

**Comment by Jermmy** [comment]
参考google的论文，qat的时候最好fold bn，这样和推理才是一致的
![image](https://user-images.githubusercontent.com/7380327/229426603-43e53441-1de9-40f3-a97c-0aa5db8489b9.png)

**Comment by CheungBH** [comment]
感谢，我去看一下。
还有个问题就是，training的时候BN为什么要这样处理？
https://github.com/Jermmy/pytorch-quantization-demo/blob/8dc1f8da75ad0ff3110eec57b96c846cd41d3462/module.py#L345
从345行到356行这

**Comment by Jermmy** [comment]
因为BN在Conv中是对输出feature的每个channel都算一个均值和方差，这个permute只是把channel换到第一维，方便对每个channel算均值和方差

**Comment by CheungBH** [comment]
<img width="733" alt="Screenshot 2023-04-03 at 8 18 06 PM" src="https://user-images.githubusercontent.com/39186017/229506785-39d90888-dc55-45b2-8240-35d77758c688.png">
那下面的这几句呢，这几句加上动量的目的是什么啊

**Comment by Jermmy** [comment]
这是BN更新均值方差的算法，可以参考下pytorch BN源码

**Comment by CheungBH** [comment]
> 这是BN更新均值方差的算法，可以参考下pytorch BN源码

谢谢，还有个问题哈。
https://github.com/Jermmy/pytorch-quantization-demo/blob/8dc1f8da75ad0ff3110eec57b96c846cd41d3462/module.py#L340
https://github.com/Jermmy/pytorch-quantization-demo/blob/8dc1f8da75ad0ff3110eec57b96c846cd41d3462/module.py#L367
这一个forward里包含两个F.conv的目的是什么

**Comment by Jermmy** [comment]
看一下我上面po的google论文图，有两个conv，第二个对应conv fold

**Comment by CheungBH** [comment]
> 看一下我上面po的google论文图，有两个conv，第二个对应conv fold

感谢。我基本明白了
