### ISSUE TITLE
how to set qo for Sigmoid layer

### ISSUE THREAD

**Issue by miccio-dk** [Jermmy/pytorch-quantization-demo#24]
Hi,
first of all, thank you so much for this very comprehensive codebase.
I was wondering: when using the newly added QSigmoid layer, how do I set the qo parameter when freezing?
Thank you so much in advance.

**Comment by Jermmy** [comment]
您好，您的邮件已收到，我会尽快查看。

**Comment by Jermmy** [comment]
Hi @miccio-dk , you could init QSigmoid with `qsigmoid = QSigmoid(qo=True)`, then `qsigmoid` will have its own `qo`. And freeze QSigmoid as `qsigmoid.freeze(qi=last_layer.qo)`, which just pass `qo=None`.

**Comment by Christian-lyc** [comment]
Sorry, I have replaced relu with separate sigmoid function in BnNet, but during quantization, the performance is very bad. Do you have any idea why this happened? Thank you so much
