### ISSUE TITLE
quant_aware training 的波动很大

### ISSUE THREAD

**Issue by qiulinzhang** [Jermmy/pytorch-quantization-demo#3]
quant_aware training的波动大约能从90% - 95% 直接波动，请问正常吗？什么都不动的情况，同一份代码跑多次，

**Comment by Jermmy** [comment]
你是跑的8bit量化吗？我自己实验低于4bit后波动会非常大，但4bit以上一般不会波动太大。

**Comment by qiulinzhang** [comment]
对，是8bit量化，就是原代码，未做任何修改，量化后的准确率能从90～95波动

**Comment by Jermmy** [comment]
我自己实验的结果是训练epoch和学习率对结果会有明显的影响，90～95之间是正常的（受数据集打乱影响，加上模型本身鲁棒性不够），波动超过10就比较大了。
