### ISSUE TITLE
这个运行的顺序是怎么样的？

### ISSUE THREAD

**Issue by ZZHHogan** [Jermmy/pytorch-quantization-demo#6]
这个运行的顺序是怎么样的？应该以怎么样顺序运行

**Comment by Jermmy** [comment]
先`python train.py`训练全精度模型，
然后可以做PTQ或者QAT，
PTQ: `python post_training_quantize.py`
QAT: `python quantization_aware_training.py`
具体可以看看我知乎或者公众号的文章：
https://mp.weixin.qq.com/s?__biz=Mzg4ODA3MDkyMA==&mid=2247483692&idx=1&sn=3e28db4881d591f4e6a66c83d4213823&chksm=cf81f74bf8f67e5d0f2a98fd7bf7a91864d14010d88a5ed89120b7b4fcd94fc34789f0d0db9a&cur_album_id=1648871870714200067&scene=190#rd
