### ISSUE TITLE
跑fashion mnist数据集，带BN的网络量化精度损失较大

### ISSUE THREAD

**Issue by gllspeed** [Jermmy/pytorch-quantization-demo#8]
你好，我这边在跑fashion mnist数据集时，带BN的网络浮点精度时88%，量化精度只有70%，精度损失比较大。不带BN的网络量化精度几乎无损。请问以下您有遇到过这种情况吗? 或者可能是什么原因呢？ 谢谢！

**Comment by Jermmy** [comment]
抱歉，现在才看到issue。之前代码中BN freeze部分有些bug，现在已经修正了，可以用新代码再试试。
